server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: '0721'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-24638736.okta.com/oauth2/default
          
      client:
        registration:
          internal-client:
           provider: okta
           authorization-grant-type: client_credentials    
           scope:
            - internal
           client-id: 0oaahxv0kxYuPPhcu5d7 
           client-secret: Vkm_04a1KW3t-tTfeZ6oZb_VA2MhuV5krmD6gL4qd5ErkdoBm03NtIX99JItOUl_
           
        provider:
          okta:
            issuer-uri:  https://dev-24638736.okta.com/oauth2/default
    
           
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9095/eureka
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always
      
      
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED   
        
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s
           

okta:
  oauth2:
    issuer: https://dev-24638736.okta.com/oauth2/default
    audience: api://default
   
        
